# Change these first
owner: MachadoConsulting # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Machado Website
    url: https://gomachado.com
    
  - name: Machado CW Manage
    url: https://na.myconnectwise.net
    
  - name: Machado CW Automate
    url: https://machado.hostedrmm.com
    icon: https://files.connectwise.com/UI/Icons/v1.0/ConnectWise-Automate-Logos-01.svg
    
  - name: Machado CW ScreenConnect
    url: https://connect.gomachado.com

  - name: Machado Voice
    url: https://phones.gomachado.com

  - name: ITGlue
    url: https://machado.itglue.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gomachado.com
  # baseUrl: /your-repo-name
  favicon: https://avatars.githubusercontent.com/u/70292154?v=4
  theme: night
  logoUrl: https://avatars.githubusercontent.com/u/70292154?v=4
  name: Machado Status
  introTitle: "Welcome to our status page."
  introMessage: "This page shows the status of all Machado's systems and will be updated with issues and resolutions as they arise."
  navbar:
    - title: Machado Status
      href: /
    - title: Website
      href: https://gomachado.com
    - title: Client Portal
      href: https://portal.gomachado.com
    - title: Contact Us
      href: mailto:help@gomachado.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
