# Change these first
owner: MachadoConsulting # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Machado Website
    url: https://gomachado.com
    
  - name: Machado CW Manage
    url: https://na.myconnectwise.net
    
  - name: Machado CW Automate
    url: https://machado.hostedrmm.com
    icon: https://www.connectwise.com/globalassets/media/archive/brand-guidelines-2021/2021-icons/color/automate-logo.png
    
  - name: Machado CW ScreenConnect
    url: https://connect.gomachado.com

  - name: Machado Voice
    url: https://phones.gomachado.com

  - name: Immybot
    url: https://machado.immy.bot
    
  - name: ITGlue
    url: https://machado.itglue.com
    icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAh1BMVEX///8FBwgAAABbXFzk5OTMzMw7PDzExMSpqan8/Pw+Pz+BgYL5+fkAAwTy8vLf39+Pj5BiY2NoaWl5enqvsLDW1ta2trafn580NTZHSEhRUlIrLC309PR0dHXs7Oy9vb2Wl5cTFBUeHyASExQtLi9WV1iamptMTU2Hh4caGxyRkZKjpKQeHx8MqWqYAAAHS0lEQVR4nO2da1fiMBCGaZRFLsW7iwsiCt79/79vu55jm5mSl0TTZGTn/aScQvo0aTO3pL2eSqVSqVQqlUqlUqlUKpVKpVKpVCqVSqVSqVQqlSqPpn0JmnbGd3hWGAkqT4+7AVxVP15IUHUeJ10Ajk2ZG62ROYsPuJLRf5+K34vHknrwn0zse/FAVhdWhA9xAQ+FPGQaleYwKuGFNMCqE4+iEt4IJIz7OBV3G1aEB0qohETne094tfeES3HzYWzC3tneEy6l2aXRCXtH0joxOqG4cRqfcHonCzE+IZ4xOg/OpCDsPbgRzd2gU/U3rba7IJyCSdG8xW/P1q8khOh5Gtsh5UpECMdpJw3WSkV4jMbpVRctfioVYe83IDTdRdsTEvZmAPGUHjoECm43HSGKm5oBOfRtM3JpdhnabueE/fqvE9CJLxPyJWAGzEJPoHPCp2YuaLfVNHpOvtR393dwUL5zwofr+s9L93mXpk++5Y59lKFB+c4JD8yFx3kXbPQtXpyHmmveBFYCwnJZ/7MGiHT03UYz8xIQWnMBuL94SujU3YlhZl4CwsLc1v+hcUpHH4hgmT8hJ5CE0NRzwRSNUzr6gLFu3dq7lYLQToUMkPFGR5/bWDdmyZtxKwlhYc0F7vuLtwwyj9zMQ0pEOG/Gqb+TAQoArFt7l9IQFua5/gCkTI1ZkO/O3Z1YLHhDLiUiLExjMaNxSnOXwAjyz3ImI9zUn4B5oGROxjO4GAPekkOpCAvzWn/0Bs77njgZEzBO6ZECCG2LeQQQx+TbAzBOx7yp7UpGaNssqALFUBcXFDowdyQ/oW2zoKANczLApDj3CmmkJLQsEeQMP5Lvg4yAnzOckLAwT/WnIGhjvJ2M0vgEbVIS2hYzCtr4Oxm/xBEWzTh1zwO8KgtNLithhIW5qT9HwSYWIXZPLj5Bm7SEtsWM7BXuZLgvxkgc4bq2RIC9wp2Mx+8EbRIT2uMUOcMvxHUYujMCu53h1IR2YBTZKzfkR5CTsaviNzWh7QxPUNCGmmTjrwdtkhPazjAKilKTbOi+GLvGaXrC0tMZfiY/g25afMLpCW2bZVF6m2TopoU55ByElq2F7Go61S3dZUdmjYI2mQl7TwDxN/khdDHok1cWIXCGS/YIQeUcIGiTmxAG72l+AjkZd+6gTXZCOE79nQyaQ5ZFiOzqgo7T6684w/kJYfCe5idA2ZFlKskjhEEbmp9AkQFX0EYCIbKr17Rr3sPHqQRC2DW8DMV9pKPSRgQh8P94GQpyMl7578ohrMap+7w3xMlY3AMnY2vQRgYhrGDwL0N5av+wGMKhu2v8y1C2B22EEMIkEz1+AibFbZU2Ugih/0edDJQm31JpI4YQJZlY1/wJCtqIIYSPENo1qAylHbSRQwgfIbRrUPqxVcEgiBD5f6wMxd+SFUUIHyG0a47BkYY5GZIIYZzC38lg41QUIRqnczJOJ8iSpUEbUYTwEeJfhkKdYVmEIE7By1CQJUsuhjBCFKfYkCOHqCbH9riEEcKgDfX/kIXwLpgQLI/yL0MhHlf7BzMTokobWoYyLbyCNu2V5JkJYQWDf637dR0ZaE9BuQmH7goGnsnwS+u0LkRuQlhpQ88NbEhhry7m3lZ2QjjVUScDlaE06UfubeUnnIBlXWtSLjVEtbjOYs/8hDBp71+GYt209EIIIAyoDParHaMXQgIh2CvEFPRQ94i2b9pX+ygJhDBpT50MlMloIgMkbyCCEGyCFlKG0qQfL8URguVRZkYzGWicbl35KIMQBm1W5Eg0ot/rycWagoQQgrgv3w0FbOtnpR8H4ghR3Jc5GWh1cTO51E6GFEJYXOLvZDSTy+KzvlEMIQja8DIU5GQ0k8uVOEIU9+URYq/J5XOloBhCGLTxX1A7486wIEKQn+DBe7T7TRPBOhJHiFwH7mQ4Ce1lJx9TkCRC4DqElKE0lTYfRXSiCNFy7rnvglrbCPoXFZBFiFwHXuvuteCvurVlEcK9eKiTAbbYtNLk1a0tjHDhLtZjmQxQhmLX4p4YYYRw9K3IkcDJsCKtlTMsjBCMPl6GgpyMZnlUXxwhqrShy7rgKvjGCLoJ2sFnp75PCPNoNEKM3JFmu6pJwN4vHopA2DsFO8z61rrbxnrc7URjEC7Pxy6d004E7kjInjZBikEYIFSGYrppMjEhdDLQ8qivKzUhyM1xYz2SUhPC3NzGc0+bICUnnLjT+9572gRpC+HuXQK+JeCO8LKjKNpCOL846lIXyFPc7D7j7xNm2GfeanuVgjCn/Pa0+cmEwRu8/jxCtNx0TwijP08FEkYep/IIg3eT/nGEfJXRPhLq2wGV8H8jBDmhXIrs64NQYC4FbQe+W2jv5zwK2g3cR+JeYhn9zdzSOpGXw0eQsPd0Rn7f8YdWgnrRsC1uI+m2+mEJL7Isjenq7VmLx1HnwRkfjVYdvjtreZhfy/D3YalUKpVKpVKpVCqVSqVSqVQqlUqlUqlUKpVKpVKl0V8wXYOHT2TcvwAAAABJRU5ErkJggg==

  - name: UniFi Controller
    url: https://hostifi.gomachado.com
    icon: https://e7.pngegg.com/pngimages/963/790/png-clipart-ubiquiti-networks-unifi-computer-network-wireless-wi-fi-others-miscellaneous-blue.png

  - name: Rewst
    url: https:/app.rewst.io
    icon: https://media.licdn.com/dms/image/C560BAQFWx4rvTtf4rA/company-logo_200_200/0/1633783133370?e=2147483647&v=beta&t=DodE-xVw7d-40mmlfdNERJw2VcoEknrfU5VXBoc76cw
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gomachado.com
  # baseUrl: /your-repo-name
  favicon: https://avatars.githubusercontent.com/u/70292154?v=4
  theme: night
  logoUrl: https://avatars.githubusercontent.com/u/70292154?v=4
  name: Machado Status
  introTitle: "Welcome to our status page."
  introMessage: "This page shows the status of all Machado's systems and will be updated with issues and resolutions as they arise."
  navbar:
    - title: Machado Status
      href: /
    - title: Website
      href: https://gomachado.com
    - title: Client Portal
      href: https://portal.gomachado.com
    - title: Contact Us
      href: mailto:help@gomachado.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
