# Change these first
owner: MachadoConsulting # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Machado Website
    url: https://gomachado.com

  - name: Machado Portal
    url: https://portal.gomachado.com

  - name: Machado Backup Vault
    url: https://rb-machado1.rb.slc.efscloud.net
    
  - name: Machado CW Manage
    url: https://na.myconnectwise.net
    
  - name: Machado CW Automate
    url: https://machado.hostedrmm.com
    icon: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.connectwise.com%2Fcompany%2Fannouncements%2Fnow-called-connectwise-manage&psig=AOvVaw0DefudW3YTa8eBWV5FgzUu&ust=1710895711253000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCOC4yayN_4QDFQAAAAAdAAAAABAJ
    
  - name: Machado CW ScreenConnect
    url: https://connect.gomachado.com

  - name: Machado Voice
    url: https://phones.gomachado.com

  - name: DNS Filter
    url: https://dns.gomachado.com

  - name: Hudu
    url: https://gomachado.huducloud.com

  - name: Immybot
    url: https://machado.immy.bot

  - name: UniFi Controller
    url: https://hostifi.gomachado.com
    icon: https://prd-www-cdn.ubnt.com/static/favicon.ico

  - name: Rewst
    url: https:/app.rewst.io
    icon: https://app.rewst.io/favicon.ico
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gomachado.com
  # baseUrl: /your-repo-name
  favicon: https://avatars.githubusercontent.com/u/70292154?v=4
  theme: night
  logoUrl: https://avatars.githubusercontent.com/u/70292154?v=4
  name: Machado Status
  introTitle: "Welcome to our status page."
  introMessage: "This page shows the status of all Machado's systems and will be updated with issues and resolutions as they arise."
  navbar:
    - title: Machado Status
      href: /
    - title: Website
      href: https://gomachado.com
    - title: Client Portal
      href: https://portal.gomachado.com
    - title: Contact Us
      href: mailto:help@gomachado.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
